version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:lts

defaults-browsers: &defaults-browsers
  working_directory: ~/repo
  docker:
    - image: circleci/node:lts-browsers

jobs:
  test:
    <<: *defaults-browsers
    environment:
      CHROME_BIN: /usr/bin/google-chrome 
    steps:
      - checkout
      # - browser-tools/install-browser-tools:
      #     chrome-version: 103.0.5060.114
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Restore dependencies from cache
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      # Install dependencies
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --no-progress
      # Cache dependencies if they don't exist
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      # Lint the source code
      # - run:
      #     name: Lint
      #     command: yarn lint:ci
      # - store_artifacts:
      #     path: eslint.xml
      #     prefix: lint
      # Build the source code
      - run:
          name: Build
          command: yarn build
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
            
workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only: main
      - build:
          filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                only: main
      - deploy:
          requires:
            - test
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only: main